# nginx proxy address - http://172.17.0.1:59006

name: zammad
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

x-shared:
  zammad-service: &zammad-service
    image: ghcr.io/zammad/zammad:latest
    pull_policy: always
    restart: always
    logging: *default-logging
    environment: &zammad-environment
      TZ: ${TZ:-America/New_York}
      POSTGRESQL_USER: ${DB_USER_NAME:-zammad}
      POSTGRESQL_PASS: ${DB_USER_PASS:-changeme_db_password}
      POSTGRESQL_PORT: 5432
      POSTGRESQL_DB: ${DB_CREATE_DATABASE_NAME:-zammad_production}
      POSTGRESQL_OPTIONS: '?pool=50'
      POSTGRESQL_HOST: zammad-postgresql
      MEMCACHE_SERVERS: zammad-memcached:11211
      REDIS_URL: redis://zammad-redis:6379
      BACKUP_DIR: '/var/tmp/zammad'
      BACKUP_TIME: '03:00'
      HOLD_DAYS: '10'
      AUTOWIZARD_JSON: ${ZAMMAD_AUTOWIZARD_JSON:-}
      AUTOWIZARD_RELATIVE_PATH: ${ZAMMAD_AUTOWIZARD_RELATIVE_PATH:-}
      ELASTICSEARCH_ENABLED: true
      ELASTICSEARCH_HOST: zammad-elasticsearch
      ELASTICSEARCH_PORT: 9200
      ELASTICSEARCH_SCHEMA: http
      ELASTICSEARCH_NAMESPACE: zammad
      ELASTICSEARCH_REINDEX: true
      NGINX_SERVER_NAME: ${BASE_HOST_NAME:-$HOSTNAME}
      ZAMMAD_HTTP_TYPE: ${ZAMMAD_HTTP_TYPE:-http}
      RAILS_TRUSTED_PROXIES: ${ZAMMAD_RAILS_TRUSTED_PROXIES:-}
      ZAMMAD_WEB_CONCURRENCY: ${ZAMMAD_WEB_CONCURRENCY:-}
      ZAMMAD_PROCESS_SESSIONS_JOBS_WORKERS: ${ZAMMAD_PROCESS_SESSIONS_JOBS_WORKERS:-}
      ZAMMAD_PROCESS_SCHEDULED_JOBS_WORKERS: ${ZAMMAD_PROCESS_SCHEDULED_JOBS_WORKERS:-}
      ZAMMAD_PROCESS_DELAYED_JOBS_WORKERS: ${ZAMMAD_PROCESS_DELAYED_JOBS_WORKERS:-}
    volumes:
      - './volumes/data/zammad/storage:/opt/zammad/storage'
    depends_on:
      - zammad-redis
      - zammad-memcached
      - zammad-postgresql
    networks:
      - zammad

services:
  zammad-elasticsearch:
    image: elasticsearch:8.17.0
    container_name: zammad-elasticsearch
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: zammad-elasticsearch
      discovery.type: single-node
      xpack.security.enabled: 'false'
    volumes:
      - './volumes/data/db/elasticsearch:/usr/share/elasticsearch/data'
    networks:
      - zammad

  zammad-memcached:
    image: memcached:alpine
    container_name: zammad-memcached
    restart: always
    pull_policy: always
    logging: *default-logging
    command: memcached -m 256M
    environment:
      CONTAINER_NAME: zammad-memcached
    networks:
      - zammad

  zammad-postgresql:
    image: postgres:latest
    container_name: zammad-postgresql
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: zammad-postgresql
      POSTGRES_USER: ${DB_USER_NAME:-zammad}
      POSTGRES_PASSWORD: ${DB_USER_PASS:-changeme_db_password}
      POSTGRES_DB: ${DB_CREATE_DATABASE_NAME:-zammad_production}
    volumes:
      - './volumes/data/db/postgres:/var/lib/postgresql/data'
    networks:
      - zammad

  zammad-redis:
    image: redis:alpine
    container_name: zammad-redis
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      CONTAINER_NAME: zammad-redis
    volumes:
      - './volumes/data/db/redis:/data'
    networks:
      - zammad

  zammad-backup:
    <<: *zammad-service
    container_name: zammad-backup
    command: ['zammad-backup']
    user: 0:0
    environment:
      <<: *zammad-environment
      CONTAINER_NAME: zammad-backup
    volumes:
      - './volumes/data/zammad/backup:/var/tmp/zammad'
      - './volumes/data/zammad/storage:/opt/zammad/storage:ro'

  zammad-init:
    <<: *zammad-service
    container_name: zammad-init
    command: ['zammad-init']
    user: 0:0
    environment:
      <<: *zammad-environment
      CONTAINER_NAME: zammad-init
    depends_on:
      - zammad-postgresql

  zammad-nginx:
    <<: *zammad-service
    container_name: zammad-nginx
    command: ['zammad-nginx']
    environment:
      <<: *zammad-environment
      CONTAINER_NAME: zammad-nginx
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
    ports:
      - '172.17.0.1:59006:8080'
    depends_on:
      - zammad-railsserver
    networks:
      - zammad
      - proxy
      - cloudflare
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://zammad-nginx:8080'
      - 'cloudflare.hostname=zammad.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.zammad-nginx.entrypoints=http'
      - 'traefik.http.routers.zammad-nginx-secure.tls=true'
      - 'traefik.http.routers.zammad-nginx.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.zammad-nginx-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.zammad-nginx.middlewares=zammad-nginx-https-redirect'
      - 'traefik.http.routers.zammad-nginx-secure.entrypoints=https'
      - 'traefik.http.routers.zammad-nginx-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.zammad-nginx-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.zammad-nginx-secure.service=zammad-nginx'
      - 'traefik.http.services.zammad-nginx.loadbalancer.server.port=8080'

  zammad-railsserver:
    <<: *zammad-service
    container_name: zammad-railsserver
    command: ['zammad-railsserver']
    environment:
      <<: *zammad-environment
      CONTAINER_NAME: zammad-railsserver

  zammad-scheduler:
    <<: *zammad-service
    container_name: zammad-scheduler
    command: ['zammad-scheduler']
    environment:
      <<: *zammad-environment
      CONTAINER_NAME: zammad-scheduler

  zammad-websocket:
    <<: *zammad-service
    container_name: zammad-websocket
    command: ['zammad-websocket']
    environment:
      <<: *zammad-environment
      CONTAINER_NAME: zammad-websocket

networks:
  zammad:
    name: zammad
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
