# nginx proxy address - http://172.17.0.1:59006

name: zammad
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

x-shared:
  zammad-service: &zammad-service
    image: ghcr.io/zammad/zammad:latest
    pull_policy: always
    restart: always
    logging: *default-logging
    environment: &zammad-environment
      TZ: ${TZ:-America/New_York}
      POSTGRESQL_USER: ${DB_USER_NAME:-zammad}
      POSTGRESQL_PASS: ${DB_USER_PASS:-changeme_db_password}
      POSTGRESQL_PORT: 5432
      POSTGRESQL_DB: ${DB_CREATE_DATABASE_NAME:-zammad_production}
      POSTGRESQL_OPTIONS: '?pool=50'
      POSTGRESQL_HOST: zammad-postgresql
      MEMCACHE_SERVERS: zammad-memcached:11211
      REDIS_URL: redis://zammad-redis:6379
      BACKUP_DIR: '/var/tmp/zammad'
      BACKUP_TIME: '03:00'
      HOLD_DAYS: '10'
      AUTOWIZARD_JSON: ${ZAMMAD_AUTOWIZARD_JSON:-}
      AUTOWIZARD_RELATIVE_PATH: ${ZAMMAD_AUTOWIZARD_RELATIVE_PATH:-}
      ELASTICSEARCH_ENABLED: true
      ELASTICSEARCH_HOST: zammad-elasticsearch
      ELASTICSEARCH_PORT: 9200
      ELASTICSEARCH_SCHEMA: http
      ELASTICSEARCH_NAMESPACE: zammad
      ELASTICSEARCH_REINDEX: true
      ELASTICSEARCH_SSL_VERIFY: false
      NGINX_SERVER_NAME: ${BASE_HOST_NAME:-$HOSTNAME}
      NGINX_SERVER_SCHEME: ${ZAMMAD_NGINX_SCHEME:-http}
      RAILS_TRUSTED_PROXIES: ${ZAMMAD_RAILS_TRUSTED_PROXIES:-}
      ZAMMAD_WEB_CONCURRENCY: ${ZAMMAD_WEB_CONCURRENCY:-}
      ZAMMAD_SESSION_JOBS: ${ZAMMAD_SESSION_JOBS:-}
      ZAMMAD_PROCESS_SCHEDULED: ${ZAMMAD_PROCESS_SCHEDULED:-}
      ZAMMAD_PROCESS_DELAYED_JOBS_WORKERS: ${ZAMMAD_PROCESS_DELAYED_JOBS_WORKERS:-}
    volumes:
      - './volumes/data/zammad/storage:/opt/zammad/storage'
    depends_on:
      - zammad-redis
      - zammad-memcached
      - zammad-postgresql
    networks:
      - zammad

services:
  zammad-elasticsearch:
    image: bitnami/elasticsearch:latest
    container_name: zammad-elasticsearch
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      ELASTICSEARCH_ENABLE_SECURITY: 'true'
      ELASTICSEARCH_SKIP_TRANSPORT_TLS: 'true'
      ELASTICSEARCH_ENABLE_REST_TLS: 'false'
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD:-changeme_db_password}
    volumes:
      - './volumes/data/db/elasticsearch:/bitnami/elasticsearch/data'
    networks:
      - zammad

  zammad-memcached:
    image: memcached:alpine
    container_name: zammad-memcached
    restart: always
    pull_policy: always
    logging: *default-logging
    command: memcached -m 256M
    networks:
      - zammad

  zammad-postgresql:
    image: postgres:latest
    container_name: zammad-postgresql
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      POSTGRES_USER: ${DB_USER_NAME:-zammad}
      POSTGRES_PASSWORD: ${DB_USER_PASS:-changeme_db_password}
      POSTGRES_DB: ${DB_CREATE_DATABASE_NAME:-zammad_production}
    volumes:
      - './volumes/data/db/postgres:/var/lib/postgresql/data'
    networks:
      - zammad

  zammad-redis:
    image: redis:alpine
    container_name: zammad-redis
    restart: always
    pull_policy: always
    logging: *default-logging
    volumes:
      - './volumes/data/db/redis:/data'
    networks:
      - zammad

  zammad-backup:
    <<: *zammad-service
    container_name: zammad-backup
    command: ['zammad-backup']
    user: 0:0
    volumes:
      - './volumes/data/zammad/backup:/var/tmp/zammad'
      - './volumes/data/zammad/storage:/opt/zammad/storage:ro'

  zammad-init:
    <<: *zammad-service
    container_name: zammad-init
    command: ['zammad-init']
    user: 0:0
    depends_on:
      - zammad-postgresql

  zammad-nginx:
    <<: *zammad-service
    container_name: zammad-nginx
    command: ['zammad-nginx']
    ports:
      - '172.17.0.1:59006:8080'
    depends_on:
      - zammad-railsserver

  zammad-railsserver:
    <<: *zammad-service
    container_name: zammad-railsserver
    command: ['zammad-railsserver']

  zammad-scheduler:
    <<: *zammad-service
    container_name: zammad-scheduler
    command: ['zammad-scheduler']

  zammad-websocket:
    <<: *zammad-service
    container_name: zammad-websocket
    command: ['zammad-websocket']

networks:
  zammad:
    name: zammad
    external: false
